apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elibrary-ingress
  namespace: elibrary
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "3"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
spec:
  rules:
    - host: elibrary.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: elibrary-server
                port:
                  number: 80
