apiVersion: v1
kind: Service
metadata:
  name: elibrary-server-alb
  namespace: elibrary
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
spec:
  type: LoadBalancer
  selector:
    app: elibrary-server
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
