apiVersion: v1
kind: Service
metadata:
  name: elibrary-server
  namespace: elibrary
  labels:
    app: elibrary-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: elibrary-server
  sessionAffinity: None
