name: Lint, test & build Server app
on:
  workflow_dispatch: # Manual trigger
  push:
    branches-ignore: [main, prod]

permissions:
  contents: read

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  markdown-lint:
    runs-on: ubuntu-latest
    container: oven/bun:alpine
    steps:
      - uses: actions/checkout@v4
      - name: Setup dev dependencies
        run: bun install
      - name: Lint .md files
        run: bun run markdown-lint

  prettier:
    runs-on: ubuntu-latest
    container: oven/bun:alpine
    steps:
      - uses: actions/checkout@v4
      - name: Setup dev dependencies
        run: bun install
      - name: Prettier check
        run: bun run prettier:check

  eslint:
    runs-on: ubuntu-latest
    container: oven/bun:alpine
    steps:
      - uses: actions/checkout@v4
      - name: Setup dev dependencies
        run: bun install
      - name: ESLint check
        run: bun run eslint:check

  unit-test:
    runs-on: ubuntu-latest
    container: oven/bun:alpine
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: bun run test

  build:
    runs-on: ubuntu-latest
    container: oven/bun:alpine
    needs: [editorconfig, markdown-lint, prettier, eslint, unit-test]
    steps:
      - uses: actions/checkout@v4
      - name: Setup dev dependencies
        run: bun install
      - name: Build single executable file
        run: bun run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./dist/
