name: Lint, test & build Server app
on:
  push:
    branches-ignore: [main, prod]

jobs:
  Editorconfig-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  Markdown-linter:
    runs-on: ubuntu-latest
    container: oven/bun:alpine
    steps:
      - uses: actions/checkout@v4
      - name: Setup dev dependencies
        run: bun install
      - name: Lint .md files
        run: bun run markdown-lint

  Prettier-check:
    runs-on: ubuntu-latest
    container: oven/bun:alpine
    steps:
      - uses: actions/checkout@v4
      - name: Setup dev dependencies
        run: bun install
      - name: Prettier check
        run: bun run prettier:check

  ESLint-check:
    runs-on: ubuntu-latest
    container: oven/bun:alpine
    steps:
      - uses: actions/checkout@v4
      - name: Setup dev dependencies
        run: bun install
      - name: ESLint check
        run: bun run eslint:check

  Unit-tests:
    runs-on: ubuntu-latest
    container: oven/bun:alpine
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: bun run test

  Build:
    runs-on: ubuntu-latest
    container: oven/bun:alpine
    needs:
      [
        Editorconfig-checker,
        Markdown-linter,
        Prettier-check,
        ESLint-check,
        Unit-tests,
      ]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: bun run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./dist/
