name: Lint, test & build Server app
on:
  push:
    branches-ignore: [main, prod]

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  markdown-lint:
    runs-on: ubuntu-latest
    container: oven/bun:alpine
    steps:
      - uses: actions/checkout@v4
      - name: Setup dev dependencies
        run: bun install
      - name: Lint .md files
        run: bun run markdown-lint

  prettier:
    runs-on: ubuntu-latest
    container: oven/bun:alpine
    steps:
      - uses: actions/checkout@v4
      - name: Setup dev dependencies
        run: bun install
      - name: Prettier check
        run: bun run prettier:check

  eslint:
    runs-on: ubuntu-latest
    container: oven/bun:alpine
    steps:
      - uses: actions/checkout@v4
      - name: Setup dev dependencies
        run: bun install
      - name: ESLint check
        run: bun run eslint:check

  # Snyk-security:
  #   runs-on: ubuntu-latest
  #   needs: [eslint]
  #   container: oven/bun:alpine
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup dev dependencies
  #       run: bun install
  #     - name: Run Snyk scan
  #       uses: snyk/actions/node@master
  #       env:
  #         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  #       with:
  #         args: --severity-threshold=high
  #     - name: Upload Snyk results
  #       if: always()
  #       uses: github/codeql-action/upload-sarif@v2
  #       with:
  #         sarif_file: snyk.sarif
  #       continue-on-error: true

  sonarqube:
    runs-on: ubuntu-latest
    needs: [eslint]
    container: oven/bun:alpine
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup dev dependencies
        run: bun install
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_ORG_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=bun-server-demo
            -Dsonar.organization=devops-fmi-1
            -Dsonar.sources=.
            -Dsonar.sourceEncoding=UTF-8

  unit-test:
    runs-on: ubuntu-latest
    container: oven/bun:alpine
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: bun run test

  Build:
    runs-on: ubuntu-latest
    container: oven/bun:alpine
    needs: [
        editorconfig,
        markdown-lint,
        prettier,
        eslint,
        # Snyk-security,
        sonarqube,
        unit-test,
      ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup dev dependencies
        run: bun install
      - name: Build single executable file
        run: bun run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./dist/
