name: SonarQube and Snyk Analysis
on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main

permissions:
  security-events: write
  contents: read

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup bun runtime
        uses: oven-sh/setup-bun@v2.0.2
      - name: Install dependencies
        run: bun install
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_ORG_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ vars.SONARQUBE_PROJECT_KEY }}
            -Dsonar.organization=${{ vars.SONARQUBE_ORGANIZATION_KEY }}
            -Dsonar.sources=./src
            -Dsonar.tests=./tests
            -Dsonar.test.inclusions=**/*.test.ts
            -Dsonar.sourceEncoding=UTF-8

  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup bun runtime
        uses: oven-sh/setup-bun@v2.0.2
      - name: Setup dev dependencies
        run: bun install
      - name: Run Snyk scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif
        continue-on-error: true # To make sure that SARIF upload gets called
      - name: Upload Snyk results
        if: always()
        uses: github/codeql-action/upload-sarif@v4.31.9
        with:
          sarif_file: snyk.sarif
